version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - etl-network

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "19000:9000"
    environment:
      CLICKHOUSE_DB: weather_db
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: password
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - etl-network

  prefect-server:
    image: prefecthq/prefect:2-python3.11
    container_name: prefect-server
    command: prefect server start
    ports:
      - "4200:4200"
    environment:
      PREFECT_SERVER_API_HOST: "0.0.0.0"
      PREFECT_SERVER_API_PORT: "4200"
    networks:
      - etl-network

  prefect-agent:
    image: prefecthq/prefect:2-python3.11
    container_name: prefect-agent
    command: prefect agent start -q default
    environment:
      PREFECT_API_URL: "http://prefect-server:4200/api"
      MINIO_ENDPOINT: "minio:9000"
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
      MINIO_BUCKET: "weather-raw"
      CLICKHOUSE_HOST: "clickhouse"
      CLICKHOUSE_PORT: "8123"
      CLICKHOUSE_DB: "weather_db"
      CLICKHOUSE_USER: "admin"
      CLICKHOUSE_PASSWORD: "password"
      TELEGRAM_BOT_TOKEN: "8342315641:AAGLLbDELI2fWZ5onZUgYSrioriAmi_2aZY"
      TELEGRAM_CHAT_ID: "-5078092097"
    depends_on:
      - prefect-server
      - clickhouse
      - minio
    networks:
      - etl-network
    volumes:
      - ./src:/opt/prefect/src
      - ./requirements.txt:/opt/prefect/requirements.txt
    working_dir: /opt/prefect
    entrypoint: >
      sh -c "pip install -r requirements.txt &&
             prefect agent start -q default"

  jupyter:
    image: jupyter/datascience-notebook:latest
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./src:/home/jovyan/work
    networks:
      - etl-network

volumes:
  minio_data:
  clickhouse_data:

networks:
  etl-network:
    driver: bridge